### ISSUE TITLE
Reverse Always True

### ISSUE THREAD

**Issue by Xndy** [andrey-ushakov/esc_pos_bluetooth#1]
I am trying to print a text and allways reverse is true and I set to value false and the same.. help me!

**Comment by andrey-ushakov** [comment]
Thank you for reporting this. What's your printer model, please?

**Comment by Xndy** [comment]
Printer: MHT-P26

I commented the line in ticket.dart:

78: bytes += styles.reverse ? cReverseOn.codeUnits : cReverseOff.codeUnits;

But now all underline

![2020-03-10](https://user-images.githubusercontent.com/24511694/76355737-d1c98f80-62e2-11ea-9961-520e7302929a.jpg)

**Comment by andrey-ushakov** [comment]
Thanks, I gonna try to check the issue this week!
At least one other person has reported the same issue. It looks like different printer manufacturers implement ESC/POS commands in a slightly different way...

**Comment by Xndy** [comment]
I have finshed to prove in another print Model ER-80 and all it is ok ... there is not problem... !

**Comment by andrey-ushakov** [comment]
Hi @Xndy,
Thank you for your feedback! I've just updated the library which may fix the underline / reverse issues.

May I ask you to print a few test tickets using both of your printers to check if it helps, please?

**Comment by Xndy** [comment]
All it ok !!

![2020-03-11 (1)](https://user-images.githubusercontent.com/24511694/76438187-ab5e2f80-6388-11ea-81c4-a941f48cd9c2.jpeg)

**Comment by Xndy** [comment]
Thank you !!!

**Comment by andrey-ushakov** [comment]
Amazing!
If you haven't found any other issues, I'm going to add both models (MHT-P26, ER-80) into the [tested printers table](https://github.com/andrey-ushakov/esc_pos_bluetooth/blob/master/printers.md).

BTW it seems that the printer on the left doesn't support barcode printing?

**Comment by Xndy** [comment]
I dont know however I can print qr code in this printer ... and aditionally question... is it posible center image ?

 final ByteData data = await rootBundle.load('assets/logo.png');
    final Uint8List bytes = data.buffer.asUint8List();
    final Image image = decodeImage(bytes);
    ticket.image(image);

It's align  left but i would align center...

**Comment by andrey-ushakov** [comment]
I've just added this feature :)

Now images and barcodes are centered by default, but you can also pass the `align` parameter for left/right alignment.

BTW, the `PosTextAlign` enum renamed to `PosAlign`. You have to rename it in your code if you are using it somewhere.

I hope it helps!

I'm going to close this issue, but feel free to reopen it if you have any further questions or ideas!

**Comment by narate1973** [comment]
what OS are you guys testing on ?
