### ISSUE TITLE
Could not find class Ticket on version 0.3.0 - 0.4.1

### ISSUE THREAD

**Issue by verzth** [andrey-ushakov/esc_pos_bluetooth#103]
Could not find class Ticket on version 0.3.0 - 0.4.1

**Comment by verzth** [comment]
Docs not updated

**Comment by rizzellodavide** [comment]
Yes, me too. Same problem. Unable to find Ticket class!

**Comment by Andndre** [comment]
Same here, esc_pos_bluetooth: ^0.4.1
