### ISSUE TITLE
Can't find Ticket class

### ISSUE THREAD

**Issue by KunakornT** [andrey-ushakov/esc_pos_bluetooth#29]
Compiler message:
lib/main.dart:26:17: Error: 'Ticket' isn't a type.
                Ticket ticket = Ticket(PaperSize.mm80);
                ^^^^^^
lib/main.dart:26:33: Error: The method 'Ticket' isn't defined for the class '_MyAppState'.
 - '_MyAppState' is from 'package:test_printer/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Ticket'.
                Ticket ticket = Ticket(PaperSize.mm80);
                                ^^^^^^
lib/main.dart:26:40: Error: The getter 'PaperSize' isn't defined for the class '_MyAppState'.
 - '_MyAppState' is from 'package:test_printer/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'PaperSize'.
                Ticket ticket = Ticket(PaperSize.mm80);

**Comment by rishirizz** [comment]
Hey, how did you resolved this issue ?  I am also facing the same issue. Any help would be appreciated.

**Comment by andrey-ushakov** [comment]
I've just published the latest version 0.4.0 which uses Generator class instead of Ticket. This should resolve the issue. Don't hesitate to reopen the issue if need.
