### ISSUE TITLE
iOS App Closes When Search Devices

### ISSUE THREAD

**Issue by arnauete52** [andrey-ushakov/esc_pos_bluetooth#36]
Please someone can help me? My code is this:

[https://i.imgur.com/qHChMNB.jpg](url)
[https://i.imgur.com/0wKo7ky.jpg](url)
[https://i.imgur.com/bTscjY2.jpg](url)

In xCode i got this... https://i.imgur.com/ADdXu6r.jpg

And with the example given by the author of the QR Print, the same... The steps I made where: install the needed packages, pub get, create the dart and test. ¿I forgot something?

I don't know what i'm doing wrong :(

**Comment by arnauete52** [comment]
Ok, I solved this! I edited the Info.plist with the Info.plist from the example and now it worked! Tested on GOOJPRT PT-210 and works fine on both systems (Android and iOS)

**Comment by itldeveloper4** [comment]
Hello , pls can u share your code for info.plist. I'm getting same issue
