### ISSUE TITLE
Only feed functions works, no text or image output

### ISSUE THREAD

**Issue by sunnyp95** [andrey-ushakov/esc_pos_bluetooth#37]
I have a phomemo m110 label printer. It uses esc_pos commands. However, only the feed functions works. I can't get any other function to work.

**Comment by patelnirav48** [comment]
@sunnyp95 Doest it works for you?

**Comment by ss-patel** [comment]
I contacted the manufacturer and got an sdk from them for the specific model. It worked then.

**Comment by patelnirav48** [comment]
Hi, I have contacted them but they not providing flutter sdk. If you have could you please send it to me? It would be great help. Also which model have you used for same?
