### ISSUE TITLE
Print on sunmi t2 (InnerPrinter) problem

### ISSUE THREAD

**Issue by llaad26** [andrey-ushakov/esc_pos_bluetooth#42]
Hi,

Thanks for your package. I use a Sunmi T2 Terminal with a virtual bluethooth (INNERPRINTER).
When I print a ticket, a 'V0' caracter is write at each lines. Another problem when the ticket is finished, the printer cut 2 times at the end.

Thanks for your help
![20200930_092817](https://user-images.githubusercontent.com/58949320/94656150-fa0cf000-02ff-11eb-9e04-0caadfc43add.jpg)

**Comment by andrey-ushakov** [comment]
Hi,

I also use Sunmi device (Sunmi V2), I've created a separate package for it: [flutter_sunmi_printer](https://github.com/andrey-ushakov/flutter_sunmi_printer). I'm not sure if it's compatible but you could try
