### ISSUE TITLE
unable to discover divices when using skd version 29

### ISSUE THREAD

**Issue by msandwidi** [andrey-ushakov/esc_pos_bluetooth#43]
Hello everyone,
The package seems to not work when using `targetSdkVersion 29` in android. I have not tried it in ios. My project is using sdk29.  

To reproduce, change 

` defaultConfig {
        applicationId "com.example.blue"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }`

to 

` defaultConfig {
        applicationId "com.example.blue"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }`

I added the following permission and it is still not working:
  `
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/> ` 

I need your help solving this problem.

**Comment by Aathi** [comment]
@andrey-ushakov  I have got the same issue, When I tried  the example app it worked well but When I tried  with actual plugin it doesn't find the printer, Any help would be appreciated.

**Comment by Rajath4** [comment]
Use [bluetooth_thermal_printer](https://pub.dev/packages/bluetooth_thermal_printer) library

**Comment by msandwidi** [comment]
I will try that. Thank you, @Rajath4
