### ISSUE TITLE
using esc_pos_bluetooth and esc_pos_printer in 1 project

### ISSUE THREAD

**Issue by gabin8** [andrey-ushakov/esc_pos_bluetooth#52]
Getting error:
Because no versions of esc_pos_printer match >4.0.3 <5.0.0 and esc_pos_printer 4.0.3 depends on esc_pos_utils ^1.0.0, esc_pos_printer ^4.0.3 requires esc_pos_utils ^1.0.0.
And because esc_pos_bluetooth >=0.2.8 depends on esc_pos_utils ^0.3.6, esc_pos_printer ^4.0.3 is incompatible with esc_pos_bluetooth >=0.2.8.
So, because ticket_scan depends on both esc_pos_bluetooth ^0.2.8 and esc_pos_printer ^4.0.3, version solving failed.
pub get failed (1; So, because tibox depends on both esc_pos_bluetooth ^0.2.8 and esc_pos_printer ^4.0.3, version solving failed.)

**Comment by TungPT95** [comment]
hi @andrey-ushakov , any update for this ?

**Comment by MasIzzudin** [comment]
is there no update yet?
it's very annoying because esc_pos_printer and esc_pos_bluetooth can't work together with the same esc_pos_utils version.

I hope there is any update ASAP

**Comment by tehsunnliu** [comment]
+1. Looks like this community is not very active. And `esc_pos_bluetooth` has printing multiple receipts issues too.

**Comment by andrey-ushakov** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
