### ISSUE TITLE
Device list is empty when I try to Scan getting this error status=0 scannerId=9 mScannerId=0  or status=0 scannerId=11 mScannerId=0

### ISSUE THREAD

**Issue by dihsarjr** [andrey-ushakov/esc_pos_bluetooth#55]
Device list is empty when I try to Scan getting this error status=0 scannerId=9 mScannerId=0  or status=0 scannerId=11 mScannerId=0

**Comment by mochrira** [comment]
I'm done with clone this repository, and edit some stuff to get it working. The point is, for sdk version 29, it requires ACCESS_FINE_LOCATION instead only ACCESS_COARSE_LOCATION and for android 10, it requires additional ACCESS_BACKGROUND_LOCATION. This plugin just requesting ACCESS_COARSE_LOCATION. I will post here when im finish packaging the plugin and then publish it to pub.dev.

**Comment by dihsarjr** [comment]
thanks for your effort

**Comment by von-maurus** [comment]
> I'm done with clone this repository, and edit some stuff to get it working. The point is, for sdk version 29, it requires ACCESS_FINE_LOCATION instead only ACCESS_COARSE_LOCATION and for android 10, it requires additional ACCESS_BACKGROUND_LOCATION. This plugin just requesting ACCESS_COARSE_LOCATION. I will post here when im finish packaging the plugin and then publish it to pub.dev.

Hi! the "devices" list is still giving me empty results and i dont know why, blue_thermal_printer package works for me, but the problem is printing the ticket with the right parameters and I cant get it right. 

I have a PT 210 portable printer bluetooth, please help

**Comment by von-maurus** [comment]
> I'm done with clone this repository, and edit some stuff to get it working. The point is, for sdk version 29, it requires ACCESS_FINE_LOCATION instead only ACCESS_COARSE_LOCATION and for android 10, it requires additional ACCESS_BACKGROUND_LOCATION. This plugin just requesting ACCESS_COARSE_LOCATION. I will post here when im finish packaging the plugin and then publish it to pub.dev.

Hi! the "devices" list is still giving me empty results and i dont know why, blue_thermal_printer package works for me, but the problem is printing the ticket with the right parameters and I cant get it right.

EDIT: I changed to SDK 28 and it works fine. Also when I upgraded to SDK 29, edited the manifest like this:

<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/> <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/> <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
It didn't worked even with the permissions added. Any suggestions?

**Comment by mochrira** [comment]
Hi @von-maurus , you need to clone this repo and [flutter_bluetooth_basic](https://github.com/andrey-ushakov/flutter_bluetooth_basic). Place their folder side by side and then edit pubspec.yaml of esc_pos_bluetooth to depends on local flutter_bluetooth_basic like below:

`
dependencies:
  ... another depdencies
  flutter_bluetooth_basic:
    path: '../flutter_bluetooth_basic'
`

Then, you free to edit this plugin functionality. The goal is to enable fine and background location access. Here the steps:

1. Edit flutter_bluetooth_basic/android/src/main/AndroidManifest.xml like below

`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.tablemi.flutter_bluetooth_basic">
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
</manifest>
`

2. Open flutter_bluetooth_basic/android/src/main/java/com/tablemi/flutter_bluetooth_basic/FlutterBluetoothBasicPlugin.java
3. Edit line 41 to `private static final int REQUEST_FINE_LOCATION_PERMISSIONS = 34;`
4. Then replace all ACCESS_COARSE_LOCATION to ACCESS_FINE_LOCATION
5. Then, still the same file, replace all REQUEST_COARSE_LOCATION_PERMISSIONS to REQUEST_FINE_LOCATION_PERMISSIONS

Hope it helps

**Comment by ajisyahroni** [comment]
thanks @mochrira

**Comment by von-maurus** [comment]
Your solution worked fine, I'm grateful @mochrira !!!

**Comment by c0c4i** [comment]
when will you release the update?

**Comment by fakhriyuds** [comment]
> Hi @von-maurus , you need to clone this repo and [flutter_bluetooth_basic](https://github.com/andrey-ushakov/flutter_bluetooth_basic). Place their folder side by side and then edit pubspec.yaml of esc_pos_bluetooth to depends on local flutter_bluetooth_basic like below:
> 
> ```
> dependencies:
>   ... another depdencies
>   flutter_bluetooth_basic:
>     path: '../flutter_bluetooth_basic'
> ```
> 
> Then, you free to edit this plugin functionality. The goal is to enable fine and background location access. Here the steps:
> 
> 1. Edit flutter_bluetooth_basic/android/src/main/AndroidManifest.xml like below
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>   package="com.tablemi.flutter_bluetooth_basic">
>     <uses-permission android:name="android.permission.BLUETOOTH"/>
>     <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
>     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
>     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
>     <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
> </manifest>
> ```
> 
> 1. Open flutter_bluetooth_basic/android/src/main/java/com/tablemi/flutter_bluetooth_basic/FlutterBluetoothBasicPlugin.java
> 2. Edit line 41 to `private static final int REQUEST_FINE_LOCATION_PERMISSIONS = 34;`
> 3. Then replace all ACCESS_COARSE_LOCATION to ACCESS_FINE_LOCATION
> 4. Then, still the same file, replace all REQUEST_COARSE_LOCATION_PERMISSIONS to REQUEST_FINE_LOCATION_PERMISSIONS
> 
> Hope it helps

Hi, is it work for IOS too? or maybe theres somethin i should change?

**Comment by mochrira** [comment]
I dont think above steps are working for iOS, you need to do your own steps based on how to working with bluetooth in iOS
