### ISSUE TITLE
esc_pos_bluetooth ^0.2.6 error with rxdart ^0.26.0

### ISSUE THREAD

**Issue by danny2585** [andrey-ushakov/esc_pos_bluetooth#65]
[proyect] flutter pub get
Running "flutter pub get" in proyect...                          
Because esc_pos_bluetooth 0.2.8 depends on rxdart ^0.23.1 and no versions of esc_pos_bluetooth match >0.2.8 <0.3.0, esc_pos_bluetooth ^0.2.8 requires rxdart ^0.23.1.

So, because app_name depends on both rxdart ^0.26.0 and esc_pos_bluetooth ^0.2.8, version solving failed.
pub get failed (1; So, because app_name depends on both rxdart ^0.26.0 and esc_pos_bluetooth ^0.2.8, version solving failed.)
exit code 1

**Comment by apocalipse9** [comment]
Same problem here.

**Comment by zainozzaini** [comment]
Same problem due too old version of rxdart ^0.23.1 and other dependencies that use rxdart ^0.24.1, so i use temporary solution by using overriding in pubsec:
```
dependency_overrides:
  rxdart: ^0.24.1
  ```

**Comment by andrey-ushakov** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!

**Comment by RizaldiWiratama** [comment]
i have same issue when add rxdart dependency

esc_pos_bluetooth >=0.3.0 depends on rxdart ^0.26.0 and my_project depends on rxdart ^0.27.1, esc_pos_bluetooth >=0.3.0 is forbidden

and solve this by overriding the dependencies

```
dependency_overrides:
  rxdart: ^0.27.1
```
