### ISSUE TITLE
null-safe but depends on non-null-safe esc_pos_utils

### ISSUE THREAD

**Issue by jobypthomas** [andrey-ushakov/esc_pos_bluetooth#88]
@andrey-ushakov 
First, thank you for releasing the null-safe package for esc_pos_bluetooth. 
However, is depends on the non-null-safe utils - `esc_pos_utils: ^0.3.6`. Can this dependency be chanted to null safe `esc_pos_utils: ^1.1.0`

**Comment by andrey-ushakov** [comment]
I've just published the latest version 0.4.0. This should resolve the issue. Don't hesitate to reopen the issue if need.
